"""Add Flight.ofp

Revision ID: 4cd4b6eda720
Revises: 8842f2b985be
Create Date: 2018-03-24 17:20:53.908794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd4b6eda720'
down_revision = '8842f2b985be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('ofp', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'ofp')
    # ### end Alembic commands ###
