"""Initial database schema

Revision ID: 8842f2b985be
Revises: 
Create Date: 2017-10-29 05:26:10.538018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8842f2b985be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao', sa.String(length=4), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('registration', sa.String(length=10), nullable=False),
    sa.Column('max_passengers', sa.Integer(), nullable=False),
    sa.Column('max_cargo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao', sa.String(length=4), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionid', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline_icao', sa.String(length=4), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.UnicodeText(), nullable=False),
    sa.Column('flight_level', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('landing_rate', sa.Integer(), nullable=True),
    sa.Column('log', sa.UnicodeText(), nullable=True),
    sa.Column('comments', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Integer(), nullable=False),
    sa.Column('ground_speed', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('flight')
    op.drop_table('session')
    op.drop_table('airport')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
